### ISSUE TITLE
[Feature Request]more concise Chinese weekday name

### ISSUE THREAD

**Issue by liuxb** [White-Tiger/T-Clock#102]
At present we know in the Chinese environment
dddd shows 星期一,星期二,星期三,星期四,星期五,星期六,星期日
ddd shows 周一,周二,周三,周四,周五,周六,周日.
Can you please add a more concise representation that shows " 一,二,三,四,五,六,日" ?
Thanks.

**Comment by White-Tiger** [comment]
well... it's using the Windows representation... what's wrong with that?
And wouldn't your suggestion simply mean: "one, two, three, four, five, six, day/sun" ?

Though, I'll "link" this issue with #45 because it's also suggesting a more compact format.
_(I'll also close this one because of that, but you may still answer my questions here as I would like to know if that format would be understood by Chinese people)_
