### ISSUE TITLE
MSVCR100.DLL WAS NOT FOUND

### ISSUE THREAD

**Issue by nollinvoyd** [White-Tiger/T-Clock#103]
"THIS CODE EXECUTION CANNOT PROCEED BECAUSE MSVCR100.DLL WAS NOT FOUND.  REINSTALLING THE PROGRAM MAY FIX THIS PROBLEM"

The previous version 2.4.2#459-beta is fine, but I get error message when trying to launch 2.4.3#471-beta

**Comment by White-Tiger** [comment]
Just use the static build as you've done before 😉

On May 26, 2017 2:07 AM, "nollinvoyd" <notifications@github.com> wrote:

"THIS CODE EXECUTION CANNOT PROCEED BECAUSE MSVCR100.DLL WAS NOT FOUND.
REINSTALLING THE PROGRAM MAY FIX THIS PROBLEM"

The previous version 2.4.2#459-beta is fine, but I get error message when
trying to launch 2.4.3#471-beta

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/White-Tiger/T-Clock/issues/103>, or mute the thread

**Comment by nollinvoyd** [comment]
Thanks.  When I d/l'ed the static build yesterday, it was v2.4.2.

All good now.
