### ISSUE TITLE
How to uninstall this in windows 7?

### ISSUE THREAD

**Issue by naveenmh** [White-Tiger/T-Clock#107]
I see no app installed in windows control panel.
And no uninstall application from the zip file.
I installed using T-clock ZIP file.

And its forcing other icons to hide from the task bar why? 
We can't change the ON/OFF for other icons to show on task bar especially battery icon.

**Comment by White-Tiger** [comment]
It's a portable Application.. so there's no uninstall... just delete it.
Settings location: see #16

Regarding your second question, T-Clock doesn't hide any tray icons. So if it is a tray icon, T-Clock is unrelated. If it is a tray "button" on the right (or left) side of T-Clock, it might be a bug.

**Comment by naveen-fractlio** [comment]
Thanks for the reply @White-Tiger. On installing T-clock, my battery status icon disappeared and when try turning it to ON from setting its not able to do so. Its masked completely in that settings list.

Please refer the screenshot.
Thank you. :)
![temp_tclock_icon_hide](https://user-images.githubusercontent.com/11418556/29061114-13cbc656-7c3a-11e7-9d29-52775bcfecf7.png)

**Comment by White-Tiger** [comment]
well... T-Clock is all about the clock, so it doesn't have anything to do with that.
The "Power" option is only available if your PC got a battery.. such as a Laptop, Tablet or PC with an uninterruptible power supply.

But since I'm not using Windows 7 anymore _(nor do I own any battery powered device running Windows)_, I can't really help you with that.
