### ISSUE TITLE
Windows cannot find 'misc\Options'

### ISSUE THREAD

**Issue by pbb72** [White-Tiger/T-Clock#135]
I am regularly getting this pop-up, without me interacting with T-Clock. Right-clicking on the taskbar entry shows that it is T-Clock launching this process.

x64 version 2.4.3 build 471.

![image](https://user-images.githubusercontent.com/1436366/35584389-361ab3f8-05f5-11e8-96aa-7676e257834d.png)

**Comment by White-Tiger** [comment]
well... what it says.
If there's an `Options.exe` wthin T-Clock's `misc/` folder, then it's a bug, if not, make sure that all T-Clock files are properly extracted.

**Comment by pbb72** [comment]
Thanks. It did not at all occur to me that misc\Options is a file path! Further investigation shows that I am actually running T-Clock from a temporary zip-autoextract folder from which all other files have been deleted.

It looks there is more people having the same problem (https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/windows-cannot-find-miscoptions/99e331ba-203a-464a-aadb-101744b8ce6a). Maybe T-Clock should do a check at startup to see if all required files are available?

I am guessing you have no control over the contents of this warning dialog. If you do, it should mention T-Clock, so that it is easier to find the cause of the problem.

**Comment by White-Tiger** [comment]
well.. this dialog is indeed auto-genereated. _(hence, "Windows couldn't")_
I could tell Windows to not generate one... but would have to implement a similar dialog myself in that case...
_(which would be missing proper localization)_
And thank you for your research and Microsoft links.

Though, this type of error is usually a user issue, so I wouldn't want to increase T-Clocks size because files are missing... Yet an AV might also delete it _(basically the only reasons that didn't involve the user)_, so some kind of improvement might be nice... _(Not sure if and how though... because `Options` is meant to become T-Clock's properties... so users might notice that it's missing eventually xD Basically on T-Clock's first run anyway)_

How did you try to extract T-Clock the first time? Even then, T-Clock should check for updates just after closing the properties dialog which pops up... _(or a few minutes after startup)_ So it should be obvious that it's T-Clock

**Comment by pbb72** [comment]
I might have used Directory Opus' ZIP-handler, or maybe 7-Zip. Many ZIP-extractors have a "try out" function, when you try to open an exectuable from the ZIP file, then the whole archive is extracted to a temporary folder and the exectuable is run from there. When you close the ZIP-file afterwards, the temporary folder is deleted again. Except of course, if the executable is still running, then that file (and only that file) will not be deleted. Without realising it, I have set that temporarily extracted T-Clock to be run on Windows startup.

The pop-up has been coming at random times, without me interacting with T-Clock (at least, for as far as I can remember), maybe once every few days.

Yeah, I also saw the Microsoft issue is locked. They do that automatically after a few weeks of inactivity. With a bit of luck, Google will also index this GitHub issue, and then people with the same problem can read the solution here :-)
