### ISSUE TITLE
checking out the Reactos "Clock" code and update it a bit with T-Clock code ?

### ISSUE THREAD

**Issue by blackcrack** [White-Tiger/T-Clock#146]
Hy @White-Tiger ,

could you maybe add t-clock things into reactos directly, because, why not..
if this anyone could, be you it . Maybe start with a couple patches for improve the Clock
from Reactos.. the sources of reactos be directly there in github.
and there could it possible directly programming in the analog clock too..

best regards
Blacky

**Comment by White-Tiger** [comment]
it's not really resolved though ;)
I've just been saying that trying to run T-Clock crashed ReactOS.. not just its Explorer, but its entire OS without any info about the crash.

If that weren't the case, I'd look into what kind of compatibility issues T-Clock had.. but this way, it's not really easy to debug without compiling ReactOS myself.

And since you started all "this", why did you start this issue? Why ReactOS? _(I'm curious, sry)_
Also, did you mean to make T-Clock runnable under ReactOS, or to directly improve its own clock? For the later, well they won't need me to do that, it's not that "hard"... yet ReactOS was at some point meant to be as much Windows as possible and the clock basically looks like the one in Windows did.

**Comment by White-Tiger** [comment]
Small heads-up:
The crash I've been talking about is more like an assertion in ReactOS' kernel code.. _(VirtualBox's serial port comes in handy :P)_
```
*** Assertion failed: pci->fsHooks == pti->fsHooks
***   Source File: ../win32ss/user/ntuser/misc.c, line 702
```
which is caused by T-Clock removing its window hook...
https://github.com/White-Tiger/T-Clock/blob/70b111a7e879bd96ce61e330fad8057d6846578d/src/DLL/clock_api.c#L347

Though even then, all the clock does is to flicker _(well the taskbar actually)_

I haven't looked more into it, so I don't know why the assertion happens and why... didn't yet try other apps that use window hooks. I do suspect that it has to do with the DLL holding a reference to itself... but who knows.

**Comment by blackcrack** [comment]
:)
Hi René ,

you can past a patch on reactos for make it more better in the community,
as programmer do you know how it works and and longtime programmer do you know what's 
should work and what's wrong, so it is maybe not bad, to looking by self, 
with a patch to works like it should and in "actually XP/Server2003 way" 
work and how and can past this as a patch and you can say, you be also an Ros-Dev ;)
by side..  how ever, you be in able to do this with your Name, i want stay anonym..
https://github.com/reactos/reactos/tree/master/ntoskrnl

best regards
Blacky

reactos.org is become something huge in future, by side of Linux and American Factory,
maybe more big, because it's more save, without backdoors as an other WINDOWS©® NTSystem ..
