### ISSUE TITLE
Minute display does not update (Win 10)

### ISSUE THREAD

**Issue by kperala** [White-Tiger/T-Clock#19]
Using T-Clock Redux x64  2.4.0 build 384 (https://github.com/White-Tiger/T-Clock/releases/download/v2.4.0%23384-rc/T-Clock.zip) on Windows 10 Enterprise.

Problem: using whatever format the minutes don't change. It stays at 01 (format mm) or 1 (format m). Windows time is ok.

**Comment by White-Tiger** [comment]
seconds work?

**Comment by kperala** [comment]
Yes, seconds run smoothly.

**Comment by White-Tiger** [comment]
wait a second.. you've mentioned  format "mm" .. that's month..
"nn" is minutes.. so this only happens when you're using a custom format with said "mm" format?

**Comment by kperala** [comment]
Good point, I was just being stupid. I used m instead of n and I failed to properly double-check the issue. Seems there's no problem with T-Clock Redux, we can close the case. My apologies. Thanks for the fast reply, though. And thank you for the great software, keep up the good work!

**Comment by White-Tiger** [comment]
no problem, your issue was actually quite descriptive ;) Though your "stupidity" now lies here forever in the world-wide-web... Doesn't seem to be possible to remove Github issues...

I'm also not happy with `nn` btw.. Ended up using the wrong format sometimes. But there's not much to do here.. as (m)onths and (m)inutes share the same starting character.. *(unless we're using `M` for months.. but the format used to be like this since the beginning.. so hard to change now)*
