### ISSUE TITLE
How to install this on Win-10

### ISSUE THREAD

**Issue by nikethansb** [White-Tiger/T-Clock#193]
How do I install this on Win-10?? I am not able to locate any .exe file. Even the src/compile.bat file is giving me an error.

**Comment by blackcrack** [comment]
Whitey, i am so sorry !!

@nikethansb DUUUUUDDEEE...
Did you looked under Releases ?!

Code=> look on the part/line with the commits, The "=>Releases", there take you mouse and 
throws she on it .. with full power.. and if you see then a Link with v2.4.4 could you maybe 
scroll down and then could you maybe see a T-Clock.7z

and if you want ask White Tiger what's a 7zip is, should you ask google before.. and this Page it's nothing for you..
Thank you for Reading, 
good luck, have a nice Day and all the best For your live,
and a good Computer learning, because, we have all started..

Please, look bottom under the Comment Textwindow, there is a "Comment and Close issue"
Please... Use it..

**Comment by nikethansb** [comment]
Thanks blackcrack. I had just downloaded the Source code earlier. I found the clock.exe when i downloaded the zip from the release section.
