### ISSUE TITLE
Can't start T-Clock Redux

### ISSUE THREAD

**Issue by ameoverflow** [White-Tiger/T-Clock#237]
When trying to open clock.exe, nothing happens. Tried closing TranslucentTB, but it didn't help

**Comment by KaiEpic** [comment]
Same problem here!

**Comment by PhantomX165** [comment]
same here but first timer
do you just opened the exe or
but the calendar works for me

**Comment by blnky** [comment]
Same here!

**Comment by eelyuh** [comment]
Any resolution to this? Having exact same issue. Literally thinking about backing up my files and just doing a clean factory reset. Absolutely maddening having to read instructions over and over / reading through all these forums or even watching some tutorials on YouTube how to "sImPlY OpEn tHe .ExE FiLe" but on my screen absolutely nothing loads. No T-Clock dot exe files, no T-Clock Options, nothing nada zero zip. Only the trusty Win7 vibed XPCalendar.exe file. Big sad

But if I delete the zip folder and all it's extracted files (after doing a reboot since Windows won't allow in core session as something of T-Clock is running in the back but isn't showing) and upon boot re download then set up/extract from anew again, and THEN run the .exe as administrator ONLY THEN does the T Clock options window come up. And in this state I can mess with all the settings but Taskbar Clock at the bottom right remains stock, nothing changes. No right clickys no left clickys nothing brings up any menu options. And once closed doesn't ever open again until entire process is repeated.

Also, I noticed at times if I try loading the TClock.exe by repeatedly clicking on it sometimes you can catch a glimpse of a window appear and disappear again within milliseconds. It's like it only flashes the shadow of the window which the Win UI portrays behind a folder.

And yes, I've tried all the versions posted in the Releases page (after confirming any previously installed iteration has been wiped from my sys). All versions act the same.

Have been using 1st Clock (paid) for couple months since searching for such function and from the way I've seen how T-Clock should work, 1st Clock just not the same.
Please someone, @White-Tiger, anybody, please help. If money is an issue I always am willing to donate. Thanks for your time and contributions,

Cheers

**Comment by ameoverflow** [comment]
> Any resolution to this? Having exact same issue. Literally thinking about backing up my files and just doing a clean factory reset. Absolutely maddening having to read instructions over and over / reading through all these forums or even watching some tutorials on YouTube how to "sImPlY OpEn tHe .ExE FiLe" but on my screen absolutely nothing loads. No T-Clock dot exe files, no T-Clock Options, nothing nada zero zip. Only the trusty Win7 vibed XPCalendar.exe file. Big sad
> 
> But if I delete the zip folder and all it's extracted files (after doing a reboot since Windows won't allow in core session as something of T-Clock is running in the back but isn't showing) and upon boot re download then set up/extract from anew again, and THEN run the .exe as administrator ONLY THEN does the T Clock options window come up. And in this state I can mess with all the settings but Taskbar Clock at the bottom right remains stock, nothing changes. No right clickys no left clickys nothing brings up any menu options. And once closed doesn't ever open again until entire process is repeated.
> 
> Also, I noticed at times if I try loading the TClock.exe by repeatedly clicking on it sometimes you can catch a glimpse of a window appear and disappear again within milliseconds. It's like it only flashes the shadow of the window which the Win UI portrays behind a folder.
> 
> And yes, I've tried all the versions posted in the Releases page (after confirming any previously installed iteration has been wiped from my sys). All versions act the same.
> 
> Have been using 1st Clock (paid) for couple months since searching for such function and from the way I've seen how T-Clock should work, 1st Clock just not the same.
> Please someone, @White-Tiger, anybody, please help. If money is an issue I always am willing to donate. Thanks for your time and contributions,
> 
> Cheers

No, did a full reinstall and nothing
@White-Tiger

**Comment by eelyuh** [comment]
3/29/2021
Just backed up all my files and did a factory rest. Can confirm this resolves the issue. Hope this helps!
