### ISSUE TITLE
After I installed T-Clock, I saw the setup box, then nothing happened.

### ISSUE THREAD

**Issue by tarek-nas** [White-Tiger/T-Clock#242]
After I started the T-Clock EXE file, I am expecting to see an analog clock. But, I don't see anything. How to use this application?

Tarek

**Comment by blackcrack** [comment]
common, can you not read the faq ?
go on/over the clock in the systray and klick with the right mousekey ..
and please close this issue ..

**Comment by tarek-nas** [comment]
I did figure this out shortly after installation. It was not obvious though. There is a lot of instruction, but I didn't land on a section that is indicating that you must right-click on the clock on the system tray.

I think it is fair to make this clear right up-front. I spent more than 5 minutes to figure this out.

If it is mentioned somewhere, maybe I missed it. You can close this issue.

And, I think there is no need to say "common". This gives a negative impression.

Tarek

**Comment by blackcrack** [comment]
Do you have a clue how "Old" this Program is ?  
Up to now, have no many peoples a "problem" with this Program in the Systray...  
a lil' hint, White Tiger is not the first Programmer who have programming this program further ..  
and up to this, this lil pretty nice program was i am couples years before i was into Bulletin Boards Terminals over Lan   (Modem/Isdn) and have help with to distribute some Programs under Friends (because i have notice , to exist some Program's like this ) ...    
so.. 1. is this Program no longer supported since a couples of month ( I have become been informed per automail/Github ( as I have noticed) )  
and 2nd if you by self not have a solution with a patch or updating the helpfile, can you close this Tread  ..

best
