### ISSUE TITLE
Windows 10 clock layout with notification button at right side

### ISSUE THREAD

**Issue by ygoe** [White-Tiger/T-Clock#39]
Windows 10 will release an update by the end of July that moves the notification button from the left side of the clock to its right side. Most users should receive this update automatically within a few days or weeks. T-Clock does not properly handle that if the clock text is longer than the system clock's text.

This is how the clock looks by default:
![t-clock-win10notification-plain](https://cloud.githubusercontent.com/assets/868315/16255998/011ce092-384f-11e6-8f05-c6c7197a8786.png)

This is T-Clock with a format that doesn't fit into that space:
![t-clock-win10notification](https://cloud.githubusercontent.com/assets/868315/16256016/191ba872-384f-11e6-98a6-2980e61255c2.png)

Even when T-Clock is closed, it doesn't restore the original layout. A logoff and re-logon is required to get the first screenshot again. Here the mouse is hovered the system clock to highlight its dimensions.
![t-clock-win10notification-exit](https://cloud.githubusercontent.com/assets/868315/16256025/30d90608-384f-11e6-8ed6-f62af5d3953e.png)

As I'm writing this, Windows kindly provided some "advertisements" so I can also show how the notification button looks like with active items:
![t-clock-win10notification2](https://cloud.githubusercontent.com/assets/868315/16256074/99c0ff5e-384f-11e6-886b-a86db9be9155.png) vs. ![t-clock-win10notification4](https://cloud.githubusercontent.com/assets/868315/16256216/b3a78c48-3850-11e6-9b6c-25db49658f67.png)

As the time format gets longer, the notification button is completely covered. Even longer formats will be clipped:
![t-clock-win10notification3](https://cloud.githubusercontent.com/assets/868315/16256119/f1661fe6-384f-11e6-9c6a-0c67498447ee.png)

**Comment by White-Tiger** [comment]
that sounds like Microsoft did at least change the resizing behavior present since Win 95 (otherwise, it should still extend to the left)
If that mechanic is really gone, and wasn't replaced by something else, it might be quite hard (and hacky) to get it working again... in which case it's unclear if I'll get it working again. (without glitches)

Though, I'll wait for the release first as things might change before that.

**Comment by B00ze64** [comment]
There they go again with their ridiculous changes to the system tray (remember the scrolling arrows, limiting the tray to like 4 icons wide?). It looks like crap and screws-up TClock; thank you Microsoft for changing something that has worked on desktop for 20 years and making it into a phone O/S...

**Comment by ygoe** [comment]
@B00ze64 Well, according to their Insider feedback postings, users like this change very much. So I guess it's a personal thing. After all, this is not the right place for Windows bashing and every other OS has their own similar issues, too. T-Clock has always been a hack and probably will until Microsoft adds an API for that. It's about finding a creative way around that. Windows is not Open Source like Linux/KDE where you can spend weeks to change the source code and build it to have your own personal customisation.

**Comment by White-Tiger** [comment]
well.. I'll hope they'll revert most changes and go back to the good old flexible and extendable modular design...
I took a look at the insider build (slow ring) and it seems like the clock got a major downgrade... it's no longer an "independent" entity, it's now fully controlled by the surrounding control _(for the main taskbar it's the notify area, and for any additional, it's the entire taskbar that controls the clock)_
This means that the clock no longer handles it's size, it simply receives it from the outer control...

So the insider build breaks at least the following:
* Clock can no longer define its own size _(T-Clock could either hook a lot more windows and add wacky code, or write to `HKEY_CURRENT_USER\Control Panel\International\sShortTime` something like `hh:mm tt HH HH HH HH HH HH HH HH HH` which is as wide as it can get.. Though the later option messes up other stuff :P)_
* The old calendar got removed, only the new slow HTML calendar is left _(T-Clock can't open either calendar as the clock is also no longer responsible. Which also means that T-Clocks ability to restore the old calendar is now useless)_
* T-Clock can't currently display the system's default tooltip as it used to...
* T-Clock's hover effect is also gone... because the clock is no longer responsible either.
* T-Clock's secondary taskbar clocks because Windows added their own _(which is not a bad change by definition, but requires me to rewrite more stuff for Win10)_

I might just skip the "upgrade" to Windows 10... I was thankful that the old calendar was still there because it's working better and faster. I just don't want "everything" to be slow like the search function thanks to Cortana _(takes 6 seconds to enter and execute "regedit" even though it should take less than <1)_, or the explorer who needs about 6 seconds to just exit _(Ctrl-Shift-RightClick taskbar)_

**Comment by ygoe** [comment]
Well, I hope you're not giving up. The format size is the most important feature for me I guess. I don't need hover effects and other interaction, I have real calendar apps for that. Just reported my sadness to their feedback system. You might want to give it some votes if you like (it's under desktop environment, taskbar).

**Comment by qwerty12** [comment]
@White-Tiger 

It's not *all* bad, FWIW :smiley: 

* With the large taskbar enabled, the time format I personally use manages to just about fit. Although with the small taskbar enabled (a must with my 1366x768 screen), T-Clock hides the notification button with a recent build of Windows 10 (which isn't a problem for me personally since I hide the button myself anyway; all that the notification system is used for is so MS can tell me frequently that I can, in fact, install Office [who knew?!] and for Action Center to tell me endlessly that I've disabled Defender).

* Only the code from Explorer to start it got removed, but the clock itself is still present. See: ![windows 10-2016-07-04-02-33-08](https://cloud.githubusercontent.com/assets/309008/16548881/b67f0570-418f-11e6-9b97-31e2d9f1c7ba.png)

    What I have now depends on MS not removing the actual clock. I want to write the contingency code now (I have an idea in mind that may work) so that a workaround is available ~~when~~ if MS remove the actual clock. (Sadly, I have a lot of learning to do for this.)
    Regarding the click: middle-click still works to show the stopwatch. Is there really no way to detect a single-click? (I guess at the worst, `SetWinEventHook` may work.) Then at least you can show the clock/calendar yourself: it's not really a pretty way IMO but using UI Automation to call DoDefaultAction on the Automation object representing the original clock works to display the "modern" clock (I can't find the way to do it directly for the new clock, but using UIA is far less likely to break anyway). The downside you can't close the displayed clock by calling it again, but I'm not sure that that's a flaw since clicking the original clock keeps showing the calendar over and over again.

* Enabling T-Clock's custom tooltip works. I've not tested this, but I'm 95% sure I can leverage the mechanism T-Clock uses to show a custom tooltip to show the standard one instead. (Although not I personally require as I already show the day and date on the taskbar anyway.)

* The hover effect means nothing to me, especially so when compared to T-Clock's ability to fit the short date into the clock when the small taskbar is being used.

* Again, I'm only thinking of myself, but I only care about the timezone that I'm living in.

I agree with you on the rest re. Windows 10. The only reason I stick around is because of the security improvements like moving font rendering out of the kernel. But if MS mess up the Modern version of File Explorer, I'll be back on WIndows 8 (the only thing I dislike there is the really bad Open With dialog box - but at least I'll have an incentive to read my copy of K&R and actually read Petzold's book to actually learn the WinAPI so that I can replace it...)

**Comment by ygoe** [comment]
@qwerty12 You can open the Security Center in the Control Panel and click on "don't show messages about this" below each of the points you don't want to be notified of. It's there since Windows XP SP2. (English names just guessed.)

**Comment by White-Tiger** [comment]
@qwerty12 how did you manage to still call the old calendar? though even if it works, since the registry setting is now gone to enable it, it's likely to be removed anyway as it isn't in use by Windows anymore..

**Comment by qwerty12** [comment]
@ygoe Thanks. I'll remember to look in the Action Center the next time I reinstall Windows...

@White-Tiger Here's sample code to do it. It's not clean, but it works. In the case MS removes the code entirely, I left a workaround in here: copy timedate.cpl (rename to timedate64.cpl for a 64-bit build) from an older Windows version and this code will use that, instead. It's inconvenient, but I think the chance of that breaking at least seems low (although I am not a clairvoyant :-)) - although the workaround is broken now in that the "Change Date/Time" link is not displayed... If you run this with "/tooltip" on the command line, it shows the classic tooltip instead.

    // OldClock.c : Shows the old clock on newer Windows 10 builds - qwerty12
    // WTFPL. Although not required, if you use the ideas from this, 
    // a single-line comment or whatever linking back to this page would be appreciated
    
    // http://stackoverflow.com/a/4308532 - the clock looks bad otherwise...
    #pragma comment(linker,"\"/manifestdependency:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'\"")
    
    #pragma comment(linker, "/SUBSYSTEM:windows")
    #pragma comment(lib, "user32.lib")
    #pragma comment(lib, "ole32.lib")
    #pragma comment(lib, "shlwapi.lib")
    
    #include <SDKDDKVer.h>
    
    #define WIN32_LEAN_AND_MEAN             // Exclude rarely-used stuff from Windows headers
    // Windows Header Files:
    #include <windows.h>
    #include <objbase.h>
    #include <Shlwapi.h>
    #include <strsafe.h>
    
    HINSTANCE hInst;                               // current instance
    LPWSTR szTitle = L"OldClock";                  // The title bar text
    LPWSTR szWindowClass = L"OldClock";            // the main window class name
    
    ATOM                MyRegisterClass(HINSTANCE hInstance);
    BOOL                InitInstance(HINSTANCE, int);
    LRESULT CALLBACK    WndProc(HWND, UINT, WPARAM, LPARAM);
    
    #pragma region CTrayClockDefinition
    typedef struct CTrayClock CTrayClock;
    
    typedef struct CTrayClockVtbl
    {
    	BEGIN_INTERFACE
    
    	HRESULT(STDMETHODCALLTYPE *QueryInterface)(
    		__RPC__in CTrayClock * This,
    		/* [in] */ __RPC__in REFIID riid,
    		/* [annotation][iid_is][out] */
    		_COM_Outptr_  void **ppvObject);
    
    	ULONG(STDMETHODCALLTYPE *AddRef)(
    		__RPC__in CTrayClock * This);
    
    	ULONG(STDMETHODCALLTYPE *Release)(
    		__RPC__in CTrayClock * This);
    
    	HRESULT(STDMETHODCALLTYPE *ShowFlyout)(
    		__RPC__in CTrayClock * This,
    		/* [in] */ __RPC__in HWND hWndParent, // I think
    		/* [in] */ __RPC__in LPRECT rcClockLocation);
    
    	HRESULT(STDMETHODCALLTYPE *HideFlyout)(
    		__RPC__in CTrayClock * This);
    
    	HRESULT(STDMETHODCALLTYPE *ShowTooltip)(
    		__RPC__in CTrayClock * This,
    		/* [in] */ __RPC__in HWND hWndParent,
    		/* [in] */ __RPC__in LPRECT rcClockLocation);
    
    	HRESULT(STDMETHODCALLTYPE *HideTooltip)(
    		__RPC__in CTrayClock * This);
    
    	END_INTERFACE
    } CTrayClockVtbl;
    
    interface CTrayClock
    {
    	CONST_VTBL struct CTrayClockVtbl *lpVtbl;
    };
    
    #pragma endregion
    
    HMODULE loadedTimeDate = NULL;
    CTrayClock *ccTrayClock;
    BOOL actingOnTooltip;
    
    // from the T-Clock source
    HWND FindClock()
    {
    	char classname[80]; const SIZE_T tcwlLen = strlen("TrayClockWClass");
    	HWND hwndBar = FindWindowA("Shell_TrayWnd", NULL);
    	// find the clock window
    	HWND hwndChild;
    	for (hwndChild = GetWindow(hwndBar, GW_CHILD); hwndChild; hwndChild = GetWindow(hwndChild, GW_HWNDNEXT)) {
    		GetClassNameA(hwndChild, classname, sizeof(classname));
    		if (!strcmp(classname, "TrayNotifyWnd")) {
    			for (hwndChild = GetWindow(hwndChild, GW_CHILD); hwndChild; hwndChild = GetWindow(hwndChild, GW_HWNDNEXT)) {
    				GetClassNameA(hwndChild, classname, sizeof(classname));
    				if (!strncmp(classname, "TrayClockWClass", tcwlLen))
    					return hwndChild;
    			}
    			break;
    		}
    	}
    	return NULL;
    }
    
    HRESULT ensureCTC(CTrayClock **ccTrayClock)
    {
    #ifndef _M_X64
    	LPCWSTR extTimeDate = L"\\timedate.cpl";
    #else
    	LPCWSTR extTimeDate = L"\\timedate64.cpl";
    #endif
    	WCHAR exeDir[MAX_PATH];
    	CLSID CLSID_TrayClock = { 0x0A323554A, 0x0FE1, 0x4E49,{ 0x0AE, 0x0E1, 0x67, 0x22, 0x46, 0x5D, 0x79, 0x9F } };
    	IID IID_CTrayClock = { 0x7A5FCA8A, 0x76B1, 0x44C8,{ 0x0A9, 0x7C, 0x0E7, 0x17, 0x3C, 0x0CA, 0x5F, 0x4F } };
    
    	if (GetModuleFileNameW(NULL, exeDir, MAX_PATH) && GetLastError() != ERROR_INSUFFICIENT_BUFFER && PathRemoveFileSpecW(exeDir)) {
    		if (SUCCEEDED(StringCchCatW(exeDir, MAX_PATH, extTimeDate)) && PathFileExistsW(exeDir)) {
    			if ((loadedTimeDate = LoadLibrary(exeDir))) {
    				// http://stackoverflow.com/a/2466264
    				BOOL(WINAPI*DllGetClassObject)(IN REFCLSID, IN REFIID, OUT LPVOID) =
    					(BOOL(WINAPI*)(IN REFCLSID, IN REFIID, OUT LPVOID))GetProcAddress(loadedTimeDate, "DllGetClassObject");
    				if (DllGetClassObject) {
    					IClassFactory *pFactory;
    					if (SUCCEEDED(DllGetClassObject(&CLSID_TrayClock, &IID_IClassFactory, &pFactory))) {
    						HRESULT hr = pFactory->lpVtbl->CreateInstance(pFactory, NULL, &IID_CTrayClock, ccTrayClock);
    						pFactory->lpVtbl->Release(pFactory);
    						return hr;
    					}
    				}
    			}
    		}
    	}
    	return CoCreateInstance(&CLSID_TrayClock, NULL, CLSCTX_INPROC_SERVER, &IID_CTrayClock, ccTrayClock);
    }
    
    VOID CALLBACK HideWhatever(
    	_In_ HWND     hwnd,
    	_In_ UINT     uMsg,
    	_In_ UINT_PTR idEvent,
    	_In_ DWORD    dwTime
    )
    {
    	if (actingOnTooltip)
    		ccTrayClock->lpVtbl->HideTooltip(ccTrayClock);
    	else
    		ccTrayClock->lpVtbl->HideFlyout(ccTrayClock);
    }
    
    int APIENTRY wWinMain(_In_ HINSTANCE hInstance,
                         _In_opt_ HINSTANCE hPrevInstance,
                         _In_ LPWSTR    lpCmdLine,
                         _In_ int       nCmdShow)
    {
        UNREFERENCED_PARAMETER(hPrevInstance);
    
    	CoInitializeEx(NULL, COINIT_APARTMENTTHREADED);
    	if (FAILED(ensureCTC(&ccTrayClock)))
    		return FALSE;
    
    	HWND hWndTrayClock = FindClock();
    	if (!hWndTrayClock)
    		return FALSE;
    	RECT trayClockPos;
    	GetWindowRect(hWndTrayClock, &trayClockPos);
    
        MyRegisterClass(hInstance);
        if (!InitInstance (hInstance, nCmdShow))
            return FALSE;
    
    	HRESULT hr;
    	if ((actingOnTooltip = !!wcsstr(lpCmdLine, L"/tooltip")))
    		hr = ccTrayClock->lpVtbl->ShowTooltip(ccTrayClock, hWndTrayClock, &trayClockPos);
    	else
    		hr = ccTrayClock->lpVtbl->ShowFlyout(ccTrayClock, hWndTrayClock, &trayClockPos);
    	if (FAILED(hr))
    		return FALSE;

        // XXX: Just a sample of the hide functions
    	SetTimer(NULL, 0, 3000, HideWhatever);
    
    	MSG msg;
        // Main message loop:
        while (GetMessage(&msg, NULL, 0, 0))
        {
            TranslateMessage(&msg);
            DispatchMessage(&msg);
        }
    
    	ccTrayClock->lpVtbl->Release(ccTrayClock); ccTrayClock = NULL;
    	if (loadedTimeDate)
			FreeLibrary(loadedTimeDate); loadedTimeDate = NULL;
    	CoUninitialize();
    
        return (int) msg.wParam;
    }
    
    #pragma region useless boilerplate
    LRESULT CALLBACK WndProc(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
    {
    	switch (message)
    	{
    	case WM_COMMAND:
    	{
    		int wmId = LOWORD(wParam);
    		// Parse the menu selections:
    		switch (wmId)
    		{
    		case WM_CLOSE:
    			DestroyWindow(hWnd);
    			break;
    		default:
    			return DefWindowProc(hWnd, message, wParam, lParam);
    		}
    	}
    	break;
    	case WM_DESTROY:
    		PostQuitMessage(0);
    		break;
    	default:
    		return DefWindowProc(hWnd, message, wParam, lParam);
    	}
    	return 0;
    }
    
    ATOM MyRegisterClass(HINSTANCE hInstance)
    {
    	WNDCLASSEXW wcex;
    
    	wcex.cbSize = sizeof(WNDCLASSEX);
    
    	wcex.style = CS_HREDRAW | CS_VREDRAW;
    	wcex.lpfnWndProc = WndProc;
    	wcex.cbClsExtra = 0;
    	wcex.cbWndExtra = 0;
    	wcex.hInstance = hInstance;
    	wcex.hIcon = 0;
    	wcex.hCursor = 0;
    	wcex.hbrBackground = (HBRUSH)(COLOR_WINDOW + 1);
    	wcex.lpszMenuName = 0;
    	wcex.lpszClassName = szWindowClass;
    	wcex.hIconSm = 0;
    
    	return RegisterClassExW(&wcex);
    }
    
    BOOL InitInstance(HINSTANCE hInstance, int nCmdShow)
    {
    	hInst = hInstance; // Store instance handle in our global variable
    
    	HWND hWnd = CreateWindowW(szWindowClass, szTitle, WS_OVERLAPPEDWINDOW,
    		CW_USEDEFAULT, 0, CW_USEDEFAULT, 0, NULL, NULL, hInstance, NULL);
    
    	if (!hWnd)
    	{
    		return FALSE;
    	}
    
    	ShowWindow(hWnd, nCmdShow);
    	UpdateWindow(hWnd);
    
    	return TRUE;
    }
    #pragma endregion

I do hope, if of course you can fix what MS messed up WRT the clock, this motivates you slightly

**Comment by White-Tiger** [comment]
I don't really see a clean way to fix the clock.. like I said.. the clock used to handle the size through window messages which T-Clock could extend upon.
But now, it's all deeply done inside explorer using MFC and the function that's called is: `ClockButton::CalculateMinimumSize` which also calls `ClockButton::CalculateMaxTextSizes` and uses the monitor's DPI to calculate the correct size.
There's also:
`ClockButton::CalculateMaxTextSize_Time`
`ClockButton::CalculateMaxTextSize_Date`
and
`ClockButton::CalculateMaxTextSize_DayOfWeek`

all of those are also used for the 2nd+ monitor clock..

Hooking functions isn't what I'd prefer.. as there are some major issues like we'll have to dynamically calculate the functions addresses _(probably through function signatures)_, we'll have to use 3rd party libraries like EasyHook or at least an disassembler to safely hook functions _(so our trampoline doesn't cut an instruction in half which would crash)_ Which all adds lots of code T-Clock never had before and wouldn't even be safe to do nor bullet proof.
So my current idea _(while not perfect)_ is to hook the clock's parent _(notify area)_ and intercept their resize messages to simply add our clock's size difference and after resizing, move the notification button... but this requires us to know the original clock size _(shouldn't be an issue)_ and the code will only handle that single notification button... but nothing else that Microsoft might add in the future without requiring code changes. _(or any other app that adds more buttons)_
If they'd still use the old _(modular)_ window communications way, it all would still work.. no matter how much they'd add in the future..

Though I'm open for ideas ;) the update hits at the end of the month.. so there's still some time :P _(I'm currently more worried about my moths old local changes like the move to Unicode etc.)_

**Comment by addonszz** [comment]
White-Tiger "to hook the clock's parent (notify area) and intercept their resize messages to simply add our clock's size difference and after resizing"

Looks a good. At least on my windows, the current clock size is the same as the original. I use T-Clock to fix the spacing waisting the microsoft does. Example, it was like this for eons:
![image](https://cloud.githubusercontent.com/assets/13953373/16926190/0e619efa-4cfe-11e6-8ee5-c677538e1bc0.png)

Now it is like this:
![image](https://cloud.githubusercontent.com/assets/13953373/16926240/3ca4a41a-4cfe-11e6-83ad-506d464357f9.png)

**Comment by White-Tiger** [comment]
@addonszz this issue doesn't currently apply to you as it doesn't seem like you're using an Windows insider build
The issue will appear on 3rd of August

**Comment by White-Tiger** [comment]
Just an update:

I got at least the clock working again... it's a bit hacky, slower and more intrusive, but seems to get the job done.
Though the hover effect is a different story :P Seems like it'll require changes that only work on Windows 10... so it'll work on 10 _(also pre-Anniversary)_ but looks weird on 8...
I haven't yet looked at the calendar...

**Comment by mikolajek** [comment]
Can we then count for some new beta release in the foreseeable future?
What I did for my purposes at the moment, I just removed year from my date (I hate it, btw...). In my case the problem occurs only on my 4K display, the full HD one still manages to display the clock & date correctly, most likely due to relatively bigger space assigned to Windows clock in lower resolutions.

**Comment by White-Tiger** [comment]
Does that answer your question :P xD

**Comment by MrsAngelD** [comment]
Hi, where can I download the updated version with the fix?

**Comment by White-Tiger** [comment]
you couldn't until now ;)
https://github.com/White-Tiger/T-Clock/releases
which also now closes this issue :P

**Comment by MrsAngelD** [comment]
Thank you! :)

**Comment by mikolajek** [comment]
Works perfectly, that's great!
