### ISSUE TITLE
T-Clock Calendar starts week on Sunday -- needs to be configurable

### ISSUE THREAD

**Issue by bkidwell** [White-Tiger/T-Clock#4]
Most calendar display widgets and apps allow you to choose what day a week starts on.

We need a configuration option for "Week starts on = [Saturday, Sunday, Monday, ...]" in the T-Clock configuration screen.

**Comment by White-Tiger** [comment]
well... the Calendar is dependent on your system setting.. so if you change the start week for your Windows, the Calendar will also use it.

**Comment by bkidwell** [comment]
That works for me. I really thought I *had* tried that, but I hadn't, and now I'm all set. It's up to you whether there should be a tip in the dialog box, a system setting override, or nothing.

**Comment by White-Tiger** [comment]
I'll likely add an option since we've got the "First week of year" setting already.. (which will be simpler to use in next version)

I actually thought about not adding it because it's hard to fit in there :P Space wise.. there isn't really much space left. Yet you're not the only one who asked how to do it ;) And it's harder to explain where the Windows setting is, than adding something to change it from T-Clock

**Comment by White-Tiger** [comment]
solved in [latest pre-release](https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.0%23351-rc)
