### ISSUE TITLE
Custom Windows theme issue

### ISSUE THREAD

**Issue by Spode** [White-Tiger/T-Clock#47]
When using version v2.4.0 (beta 3, build 384) on Win10 Anniversary Edition with StartIsBack++ 1.3.2 and a [custom Windows theme](http://neiio.deviantart.com/art/FLURRY-oS-625318704) the clock looks ok aside from the anniversary edition spacing issue that was fixed in the newer builds:
 
![1](https://cloud.githubusercontent.com/assets/595105/17419558/515dd89c-5a9e-11e6-915d-c2d96f622a71.png)

However in the v2.4.1 builds I have this issue:

![2](https://cloud.githubusercontent.com/assets/595105/17419567/560671a6-5a9e-11e6-8c81-1a31734bfa2c.png)

**Comment by White-Tiger** [comment]
My guess is that the theme isn't properly supporting Windows 10 if that background "color" is your only issue... the clock coloring changed internally since the Anniversary update, and what I'm using now seems to work fine _(even before the update actually, although it's mostly a blind guess that works quite well :P)_
So this is probably something I can't/won't fix. But I'll still try to take a look sometime.

In the mean time, wouldn't a "transparent" color work instead?

**Comment by Spode** [comment]
Yeah custom themes for Windows are a lot more "hacky" these days than they used to be (themeing Win7 was really popular). However neiio on Deviantart seems to have it figured out with the help of StartIsBack. 

My issue is the tclock seems to "override" the taskbar background. With transparent background in the tclock settings it looks like this

**Comment by White-Tiger** [comment]
the difference is that T-Clock now also draws the themes background for the clock, not just the parent background.
That's required for the high contrast themes (but wasn't/isn't for the default theme)

And your particular theme seems to miss that part... I thought about changing the transparent color to always draw the parent's theme background, but that'll partially break the reason behind the transparent color.. or rather why I've added it in first place..

I, you would have to ask the themes creator if he knows about other (better) parts the clock should use to draw... or if he'll just fix the theme to behave like Windows would.

**Comment by Spode** [comment]
Huh, it's almost as if the theme author read about this issue here on github. Like an hour or so ago he released a new version of the theme remade from scratch, and the bug is no longer there. Didn't even get to ask him about it, heh.

**Comment by White-Tiger** [comment]
Probably good for me I guess :P Though I'd love of someone could tell me what the stock clock uses to draw itself.. Before the Win 10 anniversary update, I've been able to use the "Clock" class _(VSCLASS_CLOCK)_ with part 1 _(CLP_TIME)_. but that's broken since then...

P.S. you may close the issue if it's solved ;) like it seems

**Comment by Spode** [comment]
Yeah him recreating [the theme](http://neiio.deviantart.com/art/FLURRY-oS-2-0-625318704) from scratch surprised me quite a bit. Didn't think people had too many problems but I guess there were some issues with the first version.
