### ISSUE TITLE
'Turn off monitors on workstation lock' quirk

### ISSUE THREAD

**Issue by GTR8000** [White-Tiger/T-Clock#57]
Win10 Pro x64 Build 1607 14393.82
T-Clock Redux x64 - 2.4.1 Build 419

The 'Turn off monitors on workstation lock' feature works great, however I have found one quirk with it:

When the screensaver is active, bringing the PC back to life with a mouse movement/key press stops the screensaver and brings up the logon/lock screen. It appears that T-Clock is interpreting this as the PC being locked (which it already was), and is turning off the monitors. An additional mouse movement/key press is then required to turn the monitors back on.

I don't know if there's a way for T-Clock to distinguish between a user-initiated lock (ALT+CTRL+DEL then ENTER) vs the state of the screensaver changing from active to inactive then going to the logon/lock screen, but it seems that it's treating both events the same and is turning off the monitors when you're actually trying to unlock the PC.

Any thoughts are appreciated, thanks!

**Comment by White-Tiger** [comment]
There's not much one could do... at least nothing straight forward.
See: [WTSRegisterSessionNotification](https://msdn.microsoft.com/en-us/library/aa383841(v=vs.85).aspx)

Your problem is, that the session isn't locked while the screensaver is running.. you wouldn't be able to see it otherwise... _(since the lock screen is protected and usually not accessible by other apps)_
And unfortunately, Windows doesn't seem to tell us when a screensaver toggled it..

Well... we could further delay the monitor turn-off and see if the user had been idle the entire time... Like delaying by 3 seconds and the user being idle for at least 2.4

**Comment by dmb41crash** [comment]
I should clarify that I meant the logon screen exclusively, not the Win10 "lock" screen. I have the lock screen disabled, so I go directly to the logon screen when waking up from the screensaver (old Windows behavior before Microsoft thought up the awful lock screen).

It's not really too big a deal, I just figured I'd mention the behavior in case there were a solution for it.

Thanks!

**Comment by White-Tiger** [comment]
does this release work for you?
https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.3%23471-beta

**Comment by GTR8000** [comment]
Yes, the 5 second delay makes a big difference, thank you!

Now when the screensaver is active, and the mouse is moved, instead of immediately turning off the monitor(s) it waits 5 seconds, allowing you to log in without having to shake the mouse again to wake the monitors up.

Perfect, much appreciated fix!
