### ISSUE TITLE
 Clock64.exe Ver. 2.4.2 will not run under W/10 pro 64 bit, build  10586

### ISSUE THREAD

**Issue by PeaceByJesus** [White-Tiger/T-Clock#58]
Unzipped but Clock64.exe Ver. 2.4.2 will not run under W/10 pro 64 bit, build  10586

Unable to start..Error Oxc0000007b. I even tried as run admin and in compatibility mode for W.8. 

But ver. 2.4.1.419 runs fine with no adjustments needed. Thank God for T-Clock. Should be included by MS.

**Comment by White-Tiger** [comment]
It's possible that you need to reinstall Microsoft Visual C++ 2010 Redistributable, see [#requirements](../#requirements)
Or this this error occur with the static build?

**Comment by PeaceByJesus** [comment]
No, the static build works, and so I why would the  Visual C++  need to be reinstalled?

From what i [read](http://stackoverflow.com/questions/10492037/the-application-was-unable-to-start-correctly-0xc000007b), "You get STATUS_INVALID_IMAGE_FORMAT when a DLL can be found, but it is corrupt, or has the wrong bitness,"  "The most common cause of this error is trying to load a 64 bit DLL into a 32 bit process, or vice versa."
One programmer solved this by  "changed my PATH to have the 32-bit DLLs before the 64-bit DLLs."

**Comment by White-Tiger** [comment]
That's why I said it's a Visual C++ issue. Especially when the static build works.

Visual C++ runtimes get installed quite often by different kinds of software without asking.. eg. Steam games install them. But they happen to install older version on-top of newer versions and vice versa... this can mess up a thing here and there. So it's sadly not unusual to have 4 different Visual C++ 2010 runtimes installed, even though there are just 2 in existence.. one for 32bit and another for 64bit _(both are required for my non-static builds)_

And I bet you'll see 3 or more of Visual C++ 2010 or any other version.
This is how my PC looks like _(and I'm actively cleaning it up which is why most were installed on the same date... uninstall all, reboot, install latest...)_
![](http://i.imgur.com/iYfmIT8.png)
and as you can see, I've got an old version of 2008 installed on top of a newer version... because some stupid app _(Raptr in this case)_ decided to install it without asking _(I didn't even approve an (re)install... their updater did)_

**Comment by PeaceByJesus** [comment]
Well, this is a fairly new installation of W/10, but sure enough, I have 2 identical installations of the 2008 Visual C++, same model # but one is over 1mb, versus 876kb, and I have  2 identical installations of the 2012 Visual C++, same model # but one is  20.4 mb and the other is 17.3mb. 

That is all, so there is no 2010 version.  What do you suggest? Some of my programs may need the ones installed(?)

**Comment by White-Tiger** [comment]
closing this as invalid as I believe you're missing the Visual C++ Redistributable.
Just keep using the static build ;)

**Comment by Diedrichs** [comment]
I Have installed Microsoxt Visual C++ 2010 new, but it is the same result

Best regards
Harald

**Comment by White-Tiger** [comment]
Please do the following:
* go to T-Clock's folder *(the one with Clock.exe)*
* Shift+Right-Click empty space and choose "Open command window here"
* execute the following commands and report output here *(you can copy the output by clicking the icon on the left of the window title via `Edit->Select All` and then right-clicking the selection)*
  * `%windir%\System32\where msvcr100.dll`
  * `%windir%\SysWOW64\where msvcr100.dll`
  * `%windir%\System32\where msvcp100.dll`
  * `%windir%\SysWOW64\where msvcp100.dll`

**Comment by Diedrichs** [comment]
Re: [White-Tiger/T-Clock] Clock64.exe Ver. 2.4.2 will not run under W/10 pro 64 bit, build 10586 (#58)


Hallo René Schümann,

I hope, that I make it right!

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. Alle Rechte vorbehalten.

x:\T-Clock242>%windir%\System32\where msvcr100.dll
C:\Windows\System32\msvcr100.dll
C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static\msvcr100.dll

x:\T-Clock242>%windir%\SysWOW64\where msvcr100.dll
C:\Windows\System32\msvcr100.dll
C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static\msvcr100.dll

x:\T-Clock242>%windir%\System32\where msvcp100.dll
C:\Windows\System32\msvcp100.dll
C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static\msvcp100.dll

x:\T-Clock242>%windir%\SysWOW64\where msvcp100.dll
C:\Windows\System32\msvcp100.dll
C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static\msvcp100.dll

is the result!

Best regards
Harald

am Mittwoch, 5. Oktober 2016 um 11:01 schrieben Sie:





Please do the following:


go to T-Clock's folder (the one with Clock.exe)
Shift+Right-Click empty space and choose "Open command window here"
execute the following commands and report output here (you can copy the output by clicking the icon on the left of the window title via Edit->Select All and then right-clicking the selection) 


%windir%\System32\where msvcr100.dll
%windir%\SysWOW64\where msvcr100.dll
%windir%\System32\where msvcp100.dll
%windir%\SysWOW64\where msvcp100.dll

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.




Meine Firma: 
BLAUER.SHOP: http://www.blauer-shop.de/
Diedrichs-Datainterlay: http://www.diedrichs-datainterlay.de/
-- 
Harald Diedrichs, Frankfurter Landstr. 242a, 64291 Darmstadt, Germany
phone +49 6151 371383,  fax +49 6151 373463, 
Daten: +49 6151 373491, Handy: 0152 08707695, Skype: harald.diedrichs
Meine private Seite: http://www.harald-diedrichs.de/
Meine Gemeinde: http://www.stadtmission-arheilgen.de/


-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: 6.5.8ckt http://www.ipgpp.com/
Comment: Ich glaub's

mQGiBFWLlqIRBADseaidqZBAt6Xg3MoEuCJHB6YM0rE/VnPximOonq6juRXANj9F
4R76sS+FygVtowSZCHvVFj4jHTTateNbdhp18zufbHbFl2Iln/cdxg6xncgXhEu8
yls0jfY/LOhOhiOpNnfyuCVIdP6oi9V2/1OinruXX5qif0JV4R2YrOukQwCg/3IV
e7tVnjw4metchvq4WFmcBp0D/jyldnfidCVEgHqyWHHNrnMMIrYeCeiC2uMaVLsz
IrwkimhoeLmTRHcf7gxT3PTvRIHMo/PyFvoHlho80K4EAxRdB2PiAgfteWHoe4rC
+9deaMQiNz8w14BbKPf4QmvNLCppruuKL8xP0fJJ2tJa8EIPOB0geTwEGl2esSh9
QgjPBACFzK2DF8Iu8o1/w7ER/mJItrnDZJIi1DrBd4pox72VUCrFFqTtpSod0Tp4
gM7laOOYRGscsO0P45PGqRkscBHN8s6OzjA4ivRoLcQ+sHKq6md1lq07rvtkaBWn
YyEqfoeBSIrYX3KchmWSxXdQlemGGhAqXOxWljhgMu8nz0wsbbQwSGFyYWxkIERp
ZWRyaWNocyA8ZGllZHJpY2hzQGhhcmFsZC1kaWVkcmljaHMuZGU+iQBTBBARAgAT
BQJVi5aiCQsJCggCBwMBBAIZAQAKCRCZlOeLAe9chrGwAKDYS0Z8eiT6NJCFp+jT
GtuoCDzzPQCfY34gBRwB3ZkD7DGzFvLO4bYr68O0PUhhcmFsZCBEaWVkcmljaHMg
PGhhcmFsZF9kaWVkcmljaHNAc3RhZHRtaXNzaW9uLWFyaGVpbGdlbi5kZT6JAFAE
EBECABAFAlWLmQ4JCwkKCAIHAwEEAAoJEJmU54sB71yGof0AoOc204KlbSdy/Wgl
WKm2WQG6N2DpAKCCQyVyy1rcA/WOL5C5xec8xw0PA7QqSGFyYWxkIERpZWRyaWNo
cyA8aGFyYWxkLmRpZWRyaWNoc0B3ZWIuZGU+iQBQBBARAgAQBQJVi5kyCQsJCggC
BwMBBAAKCRCZlOeLAe9chvNdAJ9dG3H3koocwj4EnbiirrvaHBiFIQCg7e9x22Pq
pEp61x5q96GpdZScqx+0M0hhcmFsZCBEaWVkcmljaHMgPGhhcmFsZC5kaWVkcmlj
aHNAY3otZGFybXN0YWR0LmRlPokAUAQQEQIAEAUCVYuZeQkLCQoIAgcDAQQACgkQ
mZTniwHvXIYlaQCeKp3qEPgo7jtQu0RQbJnNucI5NhYAoL+yS9Ag6vzfDPF0JIAz
f8qyKV03tChIYXJhbGQgRGllZHJpY2hzIDxoYXJhbGRAZi5kaWVkcmljaHMuZGU+
iQBQBBARAgAQBQJVi5mZCQsJCggCBwMBBAAKCRCZlOeLAe9chjx1AJkBMK/LHEp/
IkvpMRtt+Y3BJXYmvACdHaVgLhC5h0V65/Y2BwSqDRJan220JkhhcmFsZCBEaWVk
cmljaHMgPGhhcmFsZEBkaWVkcmljaHMuZGU+iQBQBBARAgAQBQJVi5m6CQsJCggC
BwMBBAAKCRCZlOeLAe9chi4MAJ9eEjeiynVnf2ZF3UYQMNQzh5hq1wCg22qV4h84
FBvezhNrmV602H1jo7G0L0hhcmFsZCBEaWVkcmljaHMgPGhhcmFsZF9kaWVkcmlj
aHNAdC1vbmxpbmUuZGU+iQBQBBARAgAQBQJVi5nwCQsJCggCBwMBBAAKCRCZlOeL
Ae9choLJAJ4kuxiJtmENHqhHSSYXSAKOnSCv4wCg1sta90nZ6nJjAJN604G8IyFY
+6G0LEhhcmFsZCBEaWVkcmljaHMgPGhhcmFsZF9kaWVkcmljaHNAeWFob28uZGU+
iQBQBBARAgAQBQJVi5oSCQsJCggCBwMBBAAKCRCZlOeLAe9chvnIAKCW4PpcF0TP
kfb7fDViR2RRvIPzygCgmXFUK+4jY/u+GU/CdRkEIsCBfLm0JkhhcmFsZCBEaWVk
cmljaHMgPEhEaWVkcmljaHNAamVzdXMuZGU+iQBQBBARAgAQBQJVi5ovCQsJCggC
BwMBBAAKCRCZlOeLAe9chh90AJ4mf8SA2QzDUu1WxVBLcOhonw+qrQCeLEphow/9
oc/s84Gcu2UaRmJ+jZS0JkhhcmFsZCBEaWVkcmljaHMgPGluZm9AYmxhdWVyLXNo
b3AuZGU+iQBQBBARAgAQBQJVi5pOCQsJCggCBwMBBAAKCRCZlOeLAe9chg2pAKCp
pmM91GFXgeAaPAgyvZOg1/GQhACcDI2JL4HFh6946b/I2WlyLgC5DDq0K0hhcmFs
ZCBEaWVkcmljaHMgPGRpZWRyaWNoc0BibGF1ZXItc2hvcC5kZT6JAFAEEBECABAF
AlWLmmsJCwkKCAIHAwEEAAoJEJmU54sB71yGLqQAnRzb5HAu5IhJzOSNGZYZhyL1
ttamAJ9I1+oUnnspOwmorXN1KxVewamk/LQmSGFyYWxkIERpZWRyaWNocyA8aW5m
b0BoYXJyaXMtc2hvcC5kZT6JAFAEEBECABAFAlWLmocJCwkKCAIHAwEEAAoJEJmU
54sB71yGItsAoNHKyUti5atkgrgMYO+GHgfK5MBRAKCw23BxMgIpuC5rbgb9cT6S
gzBwALQ9SGFyYWxkIERpZWRyaWNocyA8aGFyYWxkLWRpZWRyaWNoc0BkaWVkcmlj
aHMtZGF0YWludGVybGF5LmRlPokAUAQQEQIAEAUCVYuavQkLCQoIAgcDAQQACgkQ
mZTniwHvXIY7fwCfaWfCzslmxyj1EYPRvIU0cZZSZakAoIqv/HpjhfyCOOEjbeJU
DWeUoTsVtDZIYXJhbGQgRGllZHJpY2hzIDxkaWVkcmljaHNAZGllZHJpY2hzLWRh
dGFpbnRlcmxheS5kZT6JAFAEEBECABAFAlWLotkJCwkKCAIHAwEEAAoJEJmU54sB
71yGEeEAn3WP1M3yooE8llcSoFiDiGM3gvtrAJ9jPsEaNWl6VgOY8Ped5gJbq/mI
D7kCDQRVi5aiEAgA9kJXtwh/CBdyorrWqULzBej5UxE5T7bxbrlLOCDaAadWoxTp
j0BV89AHxstDqZSt90xkhkn4DIO9ZekX1KHTUPj1WV/cdlJPPT2N286Z4VeSWc39
uK50T8X8dryDxUcwYc58yWb/Ffm7/ZFexwGq01uejaClcjrUGvC/RgBYK+X0iP1Y
TknbzSC0neSRBzZrM2w4DUUdD3yIsxx8Wy2O9vPJI8BD8KVbGI2Ou1WMuF040zT9
fBdXQ6MdGGzeMyEstSr/POGxKUAYEY18hKcKctaGxAMZyAcpesqVDNmWn6vQClCb
AkbTCD1mpF1Bn5x8vYlLIhkmuquiXsNV6TILOwACAggAsIcGuWVbfbYiPCcfzS/5
cYroAAWKSYOrx30nVsuT0jo6EDxxeJiQxq0x0xpONqnChHby0gPSri9gX1wHkBT+
d60/Adu5MY2DXrlGy0M49Td1jYE/lBLHp+q8JS3kulruQUHGLcbAoKJxXizY18sC
jjkGlYA3lHuMVWCcNUNnNlUf/MhqiFO/bXLvRo0e415PXrbDYIO9Eq0cPDYM5pAN
FyTWgT8CORC7PT1euTvc0dWZy5ftKCgmxYBNXcsPU760BgNx9kO/CakkMLQPNjst
R+MUF3JHi9krDK4dGbEVuFyRPztHSYepzJlE1JP1FyZCTGQb3HbKexERNB3TSw2V
iokARgQYEQIABgUCVYuWogAKCRCZlOeLAe9chodGAJ9Ro6pX24IdcYFFKbwiFxGr
NUPIpwCg+ibcTLnVRH3ch0PHXUIFaBS5dxw=
=DSiH
-----END PGP PUBLIC KEY BLOCK-----

**Comment by Diedrichs** [comment]
Hallo René Schümann,

I hope, that I make it right!

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. Alle Rechte vorbehalten.

x:\T-Clock242>%windir%\System32\where msvcr100.dll
C:\Windows\System32\msvcr100.dll
C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static\msvcr100.dll

x:\T-Clock242>%windir%\SysWOW64\where msvcr100.dll
C:\Windows\System32\msvcr100.dll
C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static\msvcr100.dll

x:\T-Clock242>%windir%\System32\where msvcp100.dll
C:\Windows\System32\msvcp100.dll
C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static\msvcp100.dll

x:\T-Clock242>%windir%\SysWOW64\where msvcp100.dll
C:\Windows\System32\msvcp100.dll
C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static\msvcp100.dll

is the result!

Best regards
Harald

**Comment by White-Tiger** [comment]
that's fine... can you run the following 4 commands as well? *(again from within T-Clocks folder)*
```
misc\Options --version
set PATH
set "PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\"
misc\Options --version
Clock64 /prop
```

**Comment by Diedrichs** [comment]
Re: [White-Tiger/T-Clock] Clock64.exe Ver. 2.4.2 will not run under W/10 pro 64 bit, build 10586 (#58)


Guten Tag, René Schümann,

I think, I am not right.
What are the 4 comands? There are 5 lines

Here are my results:

x:\T-Clock242>misc\Options --version
T-Clock Options v2.4.2#445-beta

x:\T-Clock242>set PATH
Path=C:\Perl\site\bin;C:\Perl\bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Program Files (x86)\Universal Extractor;C:\Program Files (x86)\Universal Extractor\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Google\Google Apps Migration\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\PDFtk\bin\;C:\Program Files (x86)\ValidatorBuddy;;C:\Users\Harald Diedrichs\AppData\Local\Microsoft\WindowsApps
Path.old=;C:\Program Files (x86)\Network Associates\PGP;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PATHset "PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\"

x:\T-Clock242>misc\Options --version
T-Clock Options v2.4.2#445-beta

x:\T-Clock242>Clock64 /prop

Sorry, I am not very "good"! :(

Best regards
Harald

am Mittwoch, 5. Oktober 2016 um 20:56 schrieben Sie:





that's fine... can you run the following 4 commands as well? (again from within T-Clocks folder)
misc\Options --version
set PATH
set "PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\"
misc\Options --version
Clock64 /prop
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.




Meine Firma: 
BLAUER.SHOP: http://www.blauer-shop.de/
Diedrichs-Datainterlay: http://www.diedrichs-datainterlay.de/
-- 
Harald Diedrichs, Frankfurter Landstr. 242a, 64291 Darmstadt, Germany
phone +49 6151 371383,  fax +49 6151 373463, 
Daten: +49 6151 373491, Handy: 0152 08707695, Skype: harald.diedrichs
Meine private Seite: http://www.harald-diedrichs.de/
Meine Gemeinde: http://www.stadtmission-arheilgen.de/


-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: 6.5.8ckt http://www.ipgpp.com/
Comment: Ich glaub's

mQGiBFWLlqIRBADseaidqZBAt6Xg3MoEuCJHB6YM0rE/VnPximOonq6juRXANj9F
4R76sS+FygVtowSZCHvVFj4jHTTateNbdhp18zufbHbFl2Iln/cdxg6xncgXhEu8
yls0jfY/LOhOhiOpNnfyuCVIdP6oi9V2/1OinruXX5qif0JV4R2YrOukQwCg/3IV
e7tVnjw4metchvq4WFmcBp0D/jyldnfidCVEgHqyWHHNrnMMIrYeCeiC2uMaVLsz
IrwkimhoeLmTRHcf7gxT3PTvRIHMo/PyFvoHlho80K4EAxRdB2PiAgfteWHoe4rC
+9deaMQiNz8w14BbKPf4QmvNLCppruuKL8xP0fJJ2tJa8EIPOB0geTwEGl2esSh9
QgjPBACFzK2DF8Iu8o1/w7ER/mJItrnDZJIi1DrBd4pox72VUCrFFqTtpSod0Tp4
gM7laOOYRGscsO0P45PGqRkscBHN8s6OzjA4ivRoLcQ+sHKq6md1lq07rvtkaBWn
YyEqfoeBSIrYX3KchmWSxXdQlemGGhAqXOxWljhgMu8nz0wsbbQwSGFyYWxkIERp
ZWRyaWNocyA8ZGllZHJpY2hzQGhhcmFsZC1kaWVkcmljaHMuZGU+iQBTBBARAgAT
BQJVi5aiCQsJCggCBwMBBAIZAQAKCRCZlOeLAe9chrGwAKDYS0Z8eiT6NJCFp+jT
GtuoCDzzPQCfY34gBRwB3ZkD7DGzFvLO4bYr68O0PUhhcmFsZCBEaWVkcmljaHMg
PGhhcmFsZF9kaWVkcmljaHNAc3RhZHRtaXNzaW9uLWFyaGVpbGdlbi5kZT6JAFAE
EBECABAFAlWLmQ4JCwkKCAIHAwEEAAoJEJmU54sB71yGof0AoOc204KlbSdy/Wgl
WKm2WQG6N2DpAKCCQyVyy1rcA/WOL5C5xec8xw0PA7QqSGFyYWxkIERpZWRyaWNo
cyA8aGFyYWxkLmRpZWRyaWNoc0B3ZWIuZGU+iQBQBBARAgAQBQJVi5kyCQsJCggC
BwMBBAAKCRCZlOeLAe9chvNdAJ9dG3H3koocwj4EnbiirrvaHBiFIQCg7e9x22Pq
pEp61x5q96GpdZScqx+0M0hhcmFsZCBEaWVkcmljaHMgPGhhcmFsZC5kaWVkcmlj
aHNAY3otZGFybXN0YWR0LmRlPokAUAQQEQIAEAUCVYuZeQkLCQoIAgcDAQQACgkQ
mZTniwHvXIYlaQCeKp3qEPgo7jtQu0RQbJnNucI5NhYAoL+yS9Ag6vzfDPF0JIAz
f8qyKV03tChIYXJhbGQgRGllZHJpY2hzIDxoYXJhbGRAZi5kaWVkcmljaHMuZGU+
iQBQBBARAgAQBQJVi5mZCQsJCggCBwMBBAAKCRCZlOeLAe9chjx1AJkBMK/LHEp/
IkvpMRtt+Y3BJXYmvACdHaVgLhC5h0V65/Y2BwSqDRJan220JkhhcmFsZCBEaWVk
cmljaHMgPGhhcmFsZEBkaWVkcmljaHMuZGU+iQBQBBARAgAQBQJVi5m6CQsJCggC
BwMBBAAKCRCZlOeLAe9chi4MAJ9eEjeiynVnf2ZF3UYQMNQzh5hq1wCg22qV4h84
FBvezhNrmV602H1jo7G0L0hhcmFsZCBEaWVkcmljaHMgPGhhcmFsZF9kaWVkcmlj
aHNAdC1vbmxpbmUuZGU+iQBQBBARAgAQBQJVi5nwCQsJCggCBwMBBAAKCRCZlOeL
Ae9choLJAJ4kuxiJtmENHqhHSSYXSAKOnSCv4wCg1sta90nZ6nJjAJN604G8IyFY
+6G0LEhhcmFsZCBEaWVkcmljaHMgPGhhcmFsZF9kaWVkcmljaHNAeWFob28uZGU+
iQBQBBARAgAQBQJVi5oSCQsJCggCBwMBBAAKCRCZlOeLAe9chvnIAKCW4PpcF0TP
kfb7fDViR2RRvIPzygCgmXFUK+4jY/u+GU/CdRkEIsCBfLm0JkhhcmFsZCBEaWVk
cmljaHMgPEhEaWVkcmljaHNAamVzdXMuZGU+iQBQBBARAgAQBQJVi5ovCQsJCggC
BwMBBAAKCRCZlOeLAe9chh90AJ4mf8SA2QzDUu1WxVBLcOhonw+qrQCeLEphow/9
oc/s84Gcu2UaRmJ+jZS0JkhhcmFsZCBEaWVkcmljaHMgPGluZm9AYmxhdWVyLXNo
b3AuZGU+iQBQBBARAgAQBQJVi5pOCQsJCggCBwMBBAAKCRCZlOeLAe9chg2pAKCp
pmM91GFXgeAaPAgyvZOg1/GQhACcDI2JL4HFh6946b/I2WlyLgC5DDq0K0hhcmFs
ZCBEaWVkcmljaHMgPGRpZWRyaWNoc0BibGF1ZXItc2hvcC5kZT6JAFAEEBECABAF
AlWLmmsJCwkKCAIHAwEEAAoJEJmU54sB71yGLqQAnRzb5HAu5IhJzOSNGZYZhyL1
ttamAJ9I1+oUnnspOwmorXN1KxVewamk/LQmSGFyYWxkIERpZWRyaWNocyA8aW5m
b0BoYXJyaXMtc2hvcC5kZT6JAFAEEBECABAFAlWLmocJCwkKCAIHAwEEAAoJEJmU
54sB71yGItsAoNHKyUti5atkgrgMYO+GHgfK5MBRAKCw23BxMgIpuC5rbgb9cT6S
gzBwALQ9SGFyYWxkIERpZWRyaWNocyA8aGFyYWxkLWRpZWRyaWNoc0BkaWVkcmlj
aHMtZGF0YWludGVybGF5LmRlPokAUAQQEQIAEAUCVYuavQkLCQoIAgcDAQQACgkQ
mZTniwHvXIY7fwCfaWfCzslmxyj1EYPRvIU0cZZSZakAoIqv/HpjhfyCOOEjbeJU
DWeUoTsVtDZIYXJhbGQgRGllZHJpY2hzIDxkaWVkcmljaHNAZGllZHJpY2hzLWRh
dGFpbnRlcmxheS5kZT6JAFAEEBECABAFAlWLotkJCwkKCAIHAwEEAAoJEJmU54sB
71yGEeEAn3WP1M3yooE8llcSoFiDiGM3gvtrAJ9jPsEaNWl6VgOY8Ped5gJbq/mI
D7kCDQRVi5aiEAgA9kJXtwh/CBdyorrWqULzBej5UxE5T7bxbrlLOCDaAadWoxTp
j0BV89AHxstDqZSt90xkhkn4DIO9ZekX1KHTUPj1WV/cdlJPPT2N286Z4VeSWc39
uK50T8X8dryDxUcwYc58yWb/Ffm7/ZFexwGq01uejaClcjrUGvC/RgBYK+X0iP1Y
TknbzSC0neSRBzZrM2w4DUUdD3yIsxx8Wy2O9vPJI8BD8KVbGI2Ou1WMuF040zT9
fBdXQ6MdGGzeMyEstSr/POGxKUAYEY18hKcKctaGxAMZyAcpesqVDNmWn6vQClCb
AkbTCD1mpF1Bn5x8vYlLIhkmuquiXsNV6TILOwACAggAsIcGuWVbfbYiPCcfzS/5
cYroAAWKSYOrx30nVsuT0jo6EDxxeJiQxq0x0xpONqnChHby0gPSri9gX1wHkBT+
d60/Adu5MY2DXrlGy0M49Td1jYE/lBLHp+q8JS3kulruQUHGLcbAoKJxXizY18sC
jjkGlYA3lHuMVWCcNUNnNlUf/MhqiFO/bXLvRo0e415PXrbDYIO9Eq0cPDYM5pAN
FyTWgT8CORC7PT1euTvc0dWZy5ftKCgmxYBNXcsPU760BgNx9kO/CakkMLQPNjst
R+MUF3JHi9krDK4dGbEVuFyRPztHSYepzJlE1JP1FyZCTGQb3HbKexERNB3TSw2V
iokARgQYEQIABgUCVYuWogAKCRCZlOeLAe9chodGAJ9Ro6pX24IdcYFFKbwiFxGr
NUPIpwCg+ibcTLnVRH3ch0PHXUIFaBS5dxw=
=DSiH
-----END PGP PUBLIC KEY BLOCK-----

**Comment by White-Tiger** [comment]
sorry.. been 5 commands ;) my bad...
Well... what happened after you've entered `Clock64 /prop` ? Did T-Clock show up?
I was hoping those 32bit commands fail _(as they're the only ones supporting command line output right now)_

**P.S.** when you're replying by email _(which I wouldn't recommend anyway)_ please skip parts such as "hello" and "regards" as well as any quotes of the previous email. This doesn't look good on the issue tracker... _(and wastes storage space)_

**Comment by Diedrichs** [comment]
Here I am again:

1.
x:\T-Clock242>misc\Options --version
T-Clock Options v2.4.2#445-beta

2.
x:\T-Clock242>set PATH
Path=C:\Perl\site\bin;C:\Perl\bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Program Files (x86)\Universal Extractor;C:\Program Files (x86)\Universal Extractor\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Google\Google Apps Migration\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\PDFtk\bin\;C:\Program Files (x86)\ValidatorBuddy;;C:\Users\Harald Diedrichs\AppData\Local\Microsoft\WindowsApps
Path.old=;C:\Program Files (x86)\Network Associates\PGP;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

3.
x:\T-Clock242>set "PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\"

4.
x:\T-Clock242>misc\Options --version
T-Clock Options v2.4.2#445-beta

5.
x:\T-Clock242>Clock64 /prop

Step 3 und 5 there is no answer from cmd

Sorry, when I am so amateurish. :(

**Comment by White-Tiger** [comment]
sorry.. you didn't had to repeat all steps over again ;)
I'm just wondering what happened after the 5th step... it should open up T-Clock's options _(hard to miss I'd say)_ or error out with `Error Oxc0000007b` as you've reported before.
One of those 2 options should occur...

**Comment by Diedrichs** [comment]
Step 5 there is no result. Nothing. with Clock64.exe normal.

But now I  have seen, that there isan downloadfile called T-Clock_static.zip.
With static-version it works.
Sorry, I had not noticed, that there are two versions.

Can you say me what ist the difference?

Best regards
Harald

**Comment by White-Tiger** [comment]
> Can you say me what ist the difference?
it's statically compiled^^ So it's the opposite of "dynamic" which means it doesn't depend on any external file _(like `msvcr100.dll` / Microsoft Visual C++ 2010 Redistributable)_
Theoretically speaking, the dynamic one should use fewer resources (RAM) since the code is shared with all programs that use the same runtime... _(that's what DLLs are for... to be shared between apps)_

Other than that.. the static one has a slightly reduced performance because it's "emulating" some API functions so it can support Windows 2000 _(but that's not really measurable)_ Though it's also compiled by GCC instead of MSVC and should be faster at the end^^

**Comment by Diedrichs** [comment]
Thank you for the answer!!!
