### ISSUE TITLE
error loading dll

### ISSUE THREAD

**Issue by andresanz** [White-Tiger/T-Clock#60]
Receiving error when loading DLL (t-clock.dll or t-clock64.dll when trying to execute associated EXE

![image](https://cloud.githubusercontent.com/assets/8781111/18203413/00bc55f0-70e5-11e6-80cf-d74bca4177b0.png)

Thanks... André

**Comment by White-Tiger** [comment]
never worked for you even just once?

**Comment by andresanz** [comment]
Nope.  I've used an older version of T-Clock forever... but since I installed the anniversary version of windows 10, it won't even start, hence my search for a new(er) fork of the tool... Including removing the old version from startup, restarting and then trying to start the new T-Clock.  Is thee an installation process that I'm missing?

**Comment by White-Tiger** [comment]
it's basically just extracting the archive... nothing needs to be removed or changed... _(you may even extract it on-top of your old T-Clock version.. though, that'll leave some zombie files around)_
There aren't that many cases that would cause this message... it'll only happen if the dll version is incorrect, a semaphore couldn't be accessed or the T-Clock.ini couldn't be converted to UTF-8 due to low memory conditions.

None of these are actually likely under normal conditions _(except the semaphore issue if multiple T-Clock instances try to run at the same time)_

Are you sure no old T-Clock is running and all files were extracted? Could you try to open the Taskmanager and close any _explorer.exe_ instance as well as any Clock,exe/Clock64.exe process?

**Comment by andresanz** [comment]
no old versions running, i downloaded a fresh copy, rebooted to make sure.  Tried to restart this new version of t-clock, and still receive the same error...

**Comment by White-Tiger** [comment]
Does the latest version: https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.2%23459-beta
still show this issue? And what error code does it output?

**Comment by andresanz** [comment]
this is the error when executing clock.exe:
![image](https://cloud.githubusercontent.com/assets/8781111/18216471/e4c119c2-7124-11e6-91fa-e9b9ab935371.png), and this is the error when running clock64.exe:
![image](https://cloud.githubusercontent.com/assets/8781111/18216489/fefae1b0-7124-11e6-8cdf-658a1d6c8974.png).

Thank you for pursuing this issue... André

**Comment by andresanz** [comment]
... and if I try to run 'options.exe' a window appears and disappears instantly...

**Comment by White-Tiger** [comment]
`options.exe` is currently used only for update checking... I haven't moved the settings yet.
It's also a console application :P that's why you're not seeing a message box _(even if it had an error)_

You might try to run `XPCalendar.exe`, or the options from a console.

Anyway, did you try the static build yet? Or the non-static? maybe the other one works.

**Comment by andresanz** [comment]
What's the difference between static and non-static?  Will try other builds tonight

André Sanz

**Comment by White-Tiger** [comment]
you didn't report back... does that mean the statically linked version worked?
It's still confusing because `Clock.exe` has the same external dependencies as `T-Clock.dll` so the static build shouldn't make any difference here. _(unless the dependency is broken)_

**Comment by andresanz** [comment]
I've tried everything, to no avail.  I've downloaded different versions, rebooted, etc.  Is there a way to fix this dependency?

**Comment by andresanz** [comment]
When i open clock.exe in Dependency Walker... Well... it throws tons of errors... Attaching the DependencyWalker export file
[Clock.zip](https://github.com/White-Tiger/T-Clock/files/464398/Clock.zip)

**Comment by White-Tiger** [comment]
there are no real errors... `API-MS-*.dll` behaves a bit differently from usual dll files... those were added in Win 8 and Dependency Walker wasn't updated yet to "know" them.

Your `Clock.exe` wouldn't have problems running... and it's the static version, so there are no dependencies _(aside from a working Windows installation)_

You could also try to turn off your AV and extract T-Clock again...

**Comment by andresanz** [comment]
turned off windows defender - no change.  Ran tclock.exe in a windows 10 clean VirtualBox - same API error

**Comment by White-Tiger** [comment]
are you sure you've got the right directory structure?

```
misc/
     Options.exe
     T-Clock.dll
     T-Clock64.dll
     XPCalendar.exe
Clock.exe
Clock64.exe
```

**Comment by andresanz** [comment]
Bingo!  That was it!  Not sure what's going on... I use 7-zip for archive management, and when you initially open the zip, it shows the MISC and WAVES folder, but upon extraction, everything goes flat into the extracted root directory.

Thanks for helping me and continuing this great tool!   -André

**Comment by White-Tiger** [comment]
hmm weird... glad you've got it fixed ;)

**Comment by mat-m** [comment]
For those who are searching:

this is because of the "Flat View" mode in 7-zip FM. When it is activated, it extracts files in Flat Mode also. Untick it and it works.

Seen with 7-zip 19.0
