### ISSUE TITLE
using the TIME format

### ISSUE THREAD

**Issue by ichigo10** [White-Tiger/T-Clock#8]
When i use the TIME in custom formats the time shows up a 24 hrs with am and pm at the end even though i set it to 12 hrs in tclock and on my system.

**Comment by White-Tiger** [comment]
make sure you've got the "12h" option checked. This option is "still" in use even when using the custom format.

**Comment by ichigo10** [comment]
The 12h option is checked and when i mean TIME i type in "TIME" and it gives the in 24h with am/pm.

**Comment by White-Tiger** [comment]
you're right... that is because T-Clock forces the 24h format.. not sure why it does that but I'll try to figure out what happens if we don't enforce it.
The code looked like:
```c
GetTimeFormat(MAKELANGID(LANG_NEUTRAL,SUBLANG_DEFAULT),
			  TIME_FORCE24HOURFORMAT, pt, NULL, s, 80);
```

Would be nice if anyone knows whether removing `TIME_FORCE24HOURFORMAT` allows it to be 24h or 12h (depending on locale), or bugs people wanting the 24h format..

**Comment by White-Tiger** [comment]
solved in [latest pre-release](https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.0%23351-rc)
