### ISSUE TITLE
Watch list bug

### ISSUE THREAD

**Issue by sergeevabc** [White-Tiger/T-Clock#82]
Could you be so kind to eliminate unknown characters next to “Remaining” label?

![][1]

[1]: https://vgy.me/zlyiic.png

**Comment by White-Tiger** [comment]
upgrade your Windows

**Comment by sergeevabc** [comment]
Why do you close issue without verify step from user? It’s not resolved yet.
Host OS is Windows 7x64 with the latest updates, what do you mean, upgrade? To what, 10?

**Comment by White-Tiger** [comment]
sadly Windows 10.... yes... I've accepted that it wouldn't "work" for Windows 2000 or XP... but also found it surprising that even Windows 7 failed...
The "unknown characters" are simply: ` ⏶ ⏷` Unicode characters that don't seem to be part of the Windows < 10 font... There's another "up" / "down" symbol that would be working for XP IIRC but it's too small in practical usage... so I'm not using it _(not even as a fallback)_
Actually I'm not sure if they're really not part of the default fonts or if Windows is simply failing, because IIRC browsers did / do show them... _(you should be able to seem them here, maybe even to display them in "advanced clock format")_

And since there's no way for me to fix it and just a minor graphical "glitch" _(but still better than nothing)_ I'll leave it as is. I might consider to add the smaller variant even though you're unlikely to determine if they're up or down, once the next version hits because it got more such list views with sorting. And if nothing works... I might use `(U) / (D)` or `+ / -` even though that looks awful.

**Comment by sergeevabc** [comment]
Actually I’m quite surprised. Being a beta tester for a couple of decades (since [FIDO][1] times), I could hardly recall another native Windows tray app without cross-platform GUI dependencies (like [QT][2]) that would introduce an obstacle related to rendering characters. Support of XP is dropped by Microsoft, but 7 is far from death and is [the current choice of the majority][3], so obviously we should revise how output of T-Clock windows is done and eliminate the issue.

[1]: https://en.wikipedia.org/wiki/FidoNet
[2]: https://en.wikipedia.org/wiki/Qt_%28software%29
[3]: https://en.wikipedia.org/wiki/Usage_share_of_operating_systems#Desktop_and_laptop_computers

**Comment by White-Tiger** [comment]
like I said.. it's a Windows issue... and I'm not willing to figure out some workarounds with dozen lines of code just to waste my time and bloat the app.... I don't know why Windows isn't able to render it properly, nor a way to fix it _(unless I'll render it entirely myself but that's a lot of work)_

**Comment by White-Tiger** [comment]
just to keep you updated... the small version released today doesn't include a Workaround for a Windows older than 10... It's mostly a bug fix release and the mentioned UI update isn't ready yet.

**Comment by sergeevabc** [comment]
> Though, I also need to mention that MSVC builds seem to be broken anyway...
What do you mean? I have unpacked latest (2.4.3) static build and executed Clock64.exe without errors.

**Comment by White-Tiger** [comment]
the "_static" is build by GCC while those 2 other archives are build by MSVC.
The *_static* build should display you something like this: □ while the other build displays 2 symbols as shown in your screenshot. And that's also true when running Windows 10.

I don't know yet how to fix my MSVC builds.. I don't really like to add a UTF-8 BOM to all my source files... *(might break Github, breaks old GCC but shouldn't break my build system)* and VS2010 doesn't seem to support any command switch like `/source-charset:utf-8`
Might have to use Unicode escape sequences within my source...

**Comment by White-Tiger** [comment]
Here you go: [v2.4.4](https://github.com/White-Tiger/T-Clock/releases/tag/v2.4.4%23492-rc)
I think that could do, what do you think?

**Comment by sergeevabc** [comment]
Eventually, the solution is found. Bravo!
