### ISSUE TITLE
Win10 calendar slides out from Main monitor despite opening it on secondary monitor

### ISSUE THREAD

**Issue by Fanolian** [White-Tiger/T-Clock#9]
OS: Win10 Pro 64bit
T-Clock Redux: 2.4.0 build 341 or 351(beta/rc) 

Steps to reproduce:
1. Equip 2 (or more) monitors.
2. Properties > Miscellaneous: Enable "Duplicate clock on each additional taskbar". Don't use T-clock's calendar.
3. On the secondary monitor/clock, try to open Win10 calendar from T-Clock.

Actual result:
Calendar first slides out on the main monitor. After the animation completes, calendar moves to secondary monitor.

Expected result:
Calendar slides out on secondary monitor and stays.

Note:
This issue also affects "Restore previous calendar" from Properties > Miscellaneous. But the animation is too quick to notice.
T-clock's own calendar is not affected.

This is a minor issue and should not block the final release of 2.4.0. Thanks for the long-awaited update!

**Comment by White-Tiger** [comment]
this is actually the expected behavior... I'm sorry about that
T-Clock doesn't interfere with Windows' calendar and instead waits for it to be created and moves it to the other monitor as "requested".

The only way to let it "look" better, would require to hook deeper into Windows or hook every window action and handle the creation / show events..
But even if I wanted all of this hooking and messing around instead of the lightweight approach we currently have. It would likely not even work for Windows' 10 own calendar.. I couldn't even say if the window is visible or not, I had to wait for a window to appear on position X as only then it is really visible.
So it might not be possible to interact with Store Apps on the required level, and even if there's a way, it would be quite complicated just to let it appear "smoothly"...

Do you really care this much about it xD?

What annoys me more right now, is that I really have to wait for Window's 10 calendar to appear using said workaround.. which means I'll wait for up to 2.5 seconds for it to appear which actually blocks T-Clock during this time. *(and believe me, it might take this long..)*
*And currently, every non-English user experiences that T-Clock waits for the full 2.5 seconds and doesn't react to clicks because their calendar is called differently.. Sadly the not even visible window title is localized, and the window class is the one used by all store apps...*
Before Windows 10, the calendar wasn't just not a store App, but it also appeared instantly and I never had to wait or anything.. I just "knew" it's there and could move it.. *(this is also why it might not flash at all)*

**P.S.** fun facts about that new calendar: it is slow, it is partially always there hiding in the background *(part of the ShellExperienceHost)*, if you'll ask Windows it is always visible even when it's not, and it starts full-screen, gets later resized and lastly repositioned..

**Comment by Fanolian** [comment]
Thanks for the explanation. I don't really care about this much. I am just reporting anomaly since it is not stated in the changelog. 
Thanks again for your effort.
